# Generated by Django 3.2.3 on 2021-05-21 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(default='', max_length=32)),
                ('autor', models.CharField(default='', max_length=32)),
                ('typ_okladki', models.CharField(choices=[('twarda', 'twarda'), ('mk', 'miękka')], default='mk', max_length=32)),
                ('wydawnictwo', models.CharField(default='', max_length=35)),
                ('data_premiery', models.DateField(null=True)),
                ('data_publikacji', models.DateTimeField(default=None)),
                ('liczba_stron', models.IntegerField(default=1)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='')),
                ('uzytkownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
