# Generated by Django 3.2.3 on 2021-05-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='typ_okladki',
            field=models.CharField(choices=[('mk', 'miękka'), ('twarda', 'twarda')], default='mk', max_length=32),
        ),
    ]
