# Generated by Django 3.2.3 on 2021-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0002_alter_ksiazka_typ_okladki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='typ_okladki',
            field=models.CharField(choices=[('twarda', 'twarda'), ('mk', 'miękka')], default='mk', max_length=32),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='zdjecie',
            field=models.ImageField(default=None, upload_to='okladki'),
        ),
    ]
